### ISSUE TITLE
how to get the SQL files (to setup the DB tables)

### ISSUE THREAD

**Issue by TiloGit** [DecisionsDev/odm-ondocker#325]
Where can we find the scripts that create the database schema and populate the tables 
https://www.ibm.com/docs/en/odm/8.11.0?topic=databases-creating-decision-server-database

for non container we can find it here `<InstallDir>/executionserver/databases`: 
```
The scripts that create the database schema and populate the tables are available in <InstallDir>/executionserver/databases:

    repository_<DatabaseName>.sql: Support for the core RuleApp and ruleset persistence.
    xomrepository_<DatabaseName>.sql: Support for the XOM libraries and resources persistence.
    trace_<DatabaseName>.sql: Support for the Decision Warehouse persistence.
    decisionrunner_<DatabaseName>.sql: Support for the Decision Runner persistence. These tables are required to run simulations in the Decision Center Business console.
```

reason is that we like to create the Tables with a certain Tablespace (not the default one) so we don't want ODM to populate them but

**Comment by alainrobert** [comment]
it is not available currently since there is no option to configure the files to be used during the creation of the RES database.
We can see how to share this resources for containers.
In the meantime, would you be able to create the default tables to get the DDL from the DB server and then recreate the tables with the tablespace you need?
